### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by k6111** [PhazeRoOman/get_thawani_response#11]
### **Describe the bug (add an image if UI bug)**
The plugin does not work once it's downloaded, uploaded, and activated on the site.

### **Which browser or device was used?**
I used a MacBook computer with the Firefox browser.

### **Steps to reproduce**

1- Download the plugin.
2- Upload the plugin to the site.
3- Activate the plugin.

### **Additional context (any extra information)**

    WordPress Version: 6.3
    WooCommerce Version: 8.0.1
    Thawani for WooCommerce Version: 1.4.1

**Comment by w7shdev** [comment]
I can not replicate the issue here.. 
m,ay I ask what do you see, are the api keys working? _activated_.

please share if there is any screenshots.. or error messages.. 


Regards

**Comment by k6111** [comment]
screenshots.. or error messages..

=

> I can not replicate the issue here.. m,ay I ask what do you see, are the api keys working? _activated_.
> 
> please share if there is any screenshots.. or error messages..
> 
> Regards

Thank you for your prompt response.

To clarify, I do not have any screenshots or error messages to share. Quite simply, the plugin does not appear on my end at all, even though it is activated.

Do you recommend any steps or actions that might help resolve this issue?

**Comment by w7shdev** [comment]
> Thank you for your prompt response.

no problem. happy to help 

> To clarify, I do not have any screenshots or error messages to share. Quite simply, the plugin does not appear on my end at all, even though it is activated.

This plugin does depend on 2 plugins 
1, Thawani for woocommerce 
2. WooCommerce 

it may be the reason of local configuration.

> Do you recommend any steps or actions that might help resolve this issue?

This plugin was created for 1 purpose only.. and to be used 1 time before going to production.. 

What I will suggest to you is to write a simple script that make the same task for you.

**Comment by k6111** [comment]
> > Thank you for your prompt response.
> 
> no problem. happy to help
> 
> > To clarify, I do not have any screenshots or error messages to share. Quite simply, the plugin does not appear on my end at all, even though it is activated.
> 
> This plugin does depend on 2 plugins 1, Thawani for woocommerce 2. WooCommerce
> 
> it may be the reason of local configuration.
> 
> > Do you recommend any steps or actions that might help resolve this issue?
> 
> This plugin was created for 1 purpose only.. and to be used 1 time before going to production..
> 
> What I will suggest to you is to write a simple script that make the same task for you.

Thank you for the insight. I have both "Thawani for WooCommerce" and "WooCommerce" plugins activated, so I am a bit puzzled by the issue.

Considering that the plugin was created for a single-use before going into production, I do appreciate your suggestion about writing a simple script. However, my expertise in scripting is limited. Do you have a recommended script or guide I could follow to achieve the same task the plugin is supposed to perform?

**Comment by w7shdev** [comment]
hey @k6111 , 

if the session, is by using Thawani Pay public keys then you can use the documentation of the plugin [Retreive sessison](https://thawani-technologies.stoplight.io/docs/thawani-ecommerce-api/50259f1e290c9-retrieve-session). the documentation also provide some code samples see what are you familiar with and run it on your machine.

Regrads
